### ISSUE TITLE
一堆bugs

### ISSUE THREAD

**Issue by JieGeLovesDengDuaLang** [CognifyDev/ClashOfGods#121]
原版职业分配所分配的职业与模组分配的职业冲突
如：小丑=>中立阵营（蓝图职业船员），但游戏分配职业为内鬼阵营

**Comment by JieGeLovesDengDuaLang** [comment]
还有不知为何职业团队的显示也显示不正确，与原版的文本一样

**Comment by commandf1** [comment]
之前是没有这个问题的 可以尝试回退代码

**Comment by JieGeLovesDengDuaLang** [comment]
好吧，阵营显示bug莫名又没了，分配职业冲突的原因是调用了`PlayerControl.SetRole(AmongUs.GameOptions.RoleTypes)`，这个方法不知为何无效（也许是内部树懒有判断？），玩家的`GameData.PlayetInfo.Role`（`RoleBehaviour`的实例）依然不会改变；采用`RoleManager.SetRole(PlayerControl, AmongUs.GameOptions.RoleTypes)`才能改变玩家职业
