### ISSUE TITLE
请使用GPL3.0许可证

### ISSUE THREAD

**Issue by JieGeLovesDengDuaLang** [CognifyDev/ClashOfGods#8]
很多模组用的都是GPL3.0许可证，建议修改一下许可证

另外稍稍看了一下你们的代码，提个建议，如果觉得这些建议没用的话请忽略：
你们的接口过多了，如果是为了搞监听器倒没什么，但是有一些不必要的监听器，比如PingTracker的监听器，完全可以在PingTrackerPatch.Postfix方法里面直接改文本，没有必要再去弄个Listener；另外，随着模组的发展，需要监听的东西越来越多，IListener接口里面的方法会越来越多，所以不建议用Listener，建议用类来监听

**Comment by commandf1** [comment]
您好，使用接口是为了方便后期的角色制作封装性。
使用GPL3.0协议不是我们的本意，此协议有传染性，即**任何使用本项目源码的，都要开源**
所以我们选择了宽松的MIT协议

未来角色制作的蓝本：
`
public class ExampleRole : Role, IListener {
           public ExampleRole() : base(....) {
                      // some code here
           }

           // some listener here
}
`

使用**属性**在我们看来不符合**面向对象**的特性

**十分感谢您的建议**，如果您有时间欢迎发送**和并请求**和我们共同开发！

**Comment by JieGeLovesDengDuaLang** [comment]
但是你们在VersionShowerListener.OnPingTrackerUpdate方法中使用了snr的代码，而snr使用的是GPL3.0协议，这意味着你们也得使用这个病毒协议

**Comment by commandf1** [comment]
感谢您的建议，我们会**删除代码**或者**更改开源协议**的，十分感谢！

**Comment by commandf1** [comment]
您好，我们最终决定使用AGPL-3.0协议，因为我们要使用一个以此协议为开源协议的类库。
使用该协议理由（来自网络）：
**AGPL-3.0（GNU Affero General Public License 3.0）是一种符合GPL-3.0的自由软件许可证，它专门适用于网络服务器上部署的软件。AGPL-3.0要求如果你使用或修改了AGPL-3.0许可的代码，并将其作为网络服务或应用提供给其他人时，你必须公开源代码。这也意味着你的整个项目都需要使用AGPL-3.0许可证。**
**GPL-3.0（GNU General Public License 3.0）是一种自由软件许可证，要求如果你使用或修改了GPL-3.0许可的代码，你必须将整个项目的源代码以GPL-3.0许可证的形式公开。然而，GPL-3.0不需要您公开网络服务的源代码。**

而我们即将使用的类库（您会在接下来的提交中见到它）涉及了网络服务，所以我们决定使用AGPL-3.0协议。
