### ISSUE TITLE
OnPlayerMuder和OnCheckMurder是一个东西

### ISSUE THREAD

**Issue by NikoCat233** [CognifyDev/ClashOfGods#99]
以我的理解，两者都是对checkmurder事件的一个基本一模一样的patch
是否考虑去除一个或者合并
我更喜欢checkmurder这个名字

**Comment by commandf1** [comment]
OnMurderPlayer是击杀完玩家之后的事情，而OnPlayerMurder是之前的事情，可以判断是否取消
也就是说后者可能被取消，而前者已经舒米煮成饭了
总的来说这种Listener方式是有些问题的，后期准备重置

**Comment by NikoCat233** [comment]
不 我的意思是OnCheckMurder和OnPlayerMurder是一样的
现有的OnPlayerMurder应该归为OnCheckMurder里面

**Comment by commandf1** [comment]
那是这样的
